# Generated by Django 5.1.1 on 2024-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('preco', models.FloatField()),
                ('codigo_de_barras', models.TextField()),
            ],
        ),
    ]
